apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-website
  annotations:
    github.com/project-slug: 'spotify-portal-demo/demo-website'
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: sharks
