apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/techdocs-ref: dir:.
  name: demo-website
spec:
  type: website
  lifecycle: experimental
  owner: spotify-portal-demo/sharks
